namespace Gedcom;

/// <summary>
/// A list of all native GEDCOM tags.
/// </summary>
public static class Tag
{
    public const string Abbreviation = "ABBR"; // {Abbreviation} <SOURCE_FILED_BY_ENTRY>
    public const string Address = "ADDR"; // {Address} <ADDRESS_LINE>
    public const string Adoption = "ADOP"; // {Adoption} <blank>
    public const string Address1 = "ADR1"; // {Address1} <ADDRESS_LINE1>
    public const string Address2 = "ADR2"; // {Address2} <ADDRESS_LINE2>
    public const string Address3 = "ADR3"; // {Address3} <ADDRESS_LINE3>
    public const string AncestralFileNumber = "AFN"; // {AFN} <ANCESTRAL_FILE_NUMBER>
    public const string Age = "AGE"; // {Age} <AGE_AT_EVENT>
    public const string Agency = "AGNC"; // {Agency} <RESPONSIBLE_AGENCY>
    public const string Alias = "ALIA"; // {Alias} @<XREF:IND>@
    public const string Ancestors = "ANCE"; // {Ancestors} <GENERATIONS_OF_ANCESTORS>
    public const string AncesInterest = "ANCI"; // {Ances Interest} @<XREF:SUBM>@
    public const string Annulment = "ANUL"; // {Annulment} <blank>
    public const string Associates = "ASSO"; // {Associates} @<XREF:INDI>@
    public const string Author = "AUTH"; // {Author} <SOURCE_ORIGINATOR>
    public const string BaptismLds = "BAPL"; // {Baptism-LDS} <blank>
    public const string Baptism = "BAPM"; // {Baptism} <blank>
    public const string BarMitzvah = "BARM"; // {Bar Mitzvah} <blank>
    public const string BasMitzvah = "BASM"; // {Bas Mitzvah} <blank>
    public const string Blessing = "BLES"; // {Blessing} <blank>
    public const string Birth = "BIRT"; // {Birth} <blank>
    public const string Both = "BOTH"; // {Both} <blank>, <ADOPTED_BY_WHICH_PARENT>
    public const string Burial = "BURI"; // {Burial} <blank>
    public const string CallNumber = "CALN"; // {Call Number} <SOURCE_CALL_NUMBER>
    public const string Caste = "CAST"; // {Caste} <CASTE_NAME>
    public const string Cause = "CAUS"; // {Cause} <CAUSE_OF_EVENT>
    public const string Census = "CENS"; // {Census} <blank>
    public const string Change = "CHAN"; // {Change} <blank>
    public const string Character = "CHAR"; // {Character} <CHARACTER_SET>
    public const string Child = "CHIL"; // {Child} @<XREF:INDI>@
    public const string Christening = "CHR"; // {Christening} <blank>
    public const string AdultChristening = "CHRA"; // {Adult Christening} <blank>
    public const string City = "CITY"; // {City} <ADDRESS_CITY>
    public const string Concatenation = "CONC"; // {Concatenation} Concatenate to previous line without a space or carriage return.
    public const string Confirmation = "CONF"; // {Confirmation} <blank>
    public const string ConfirmationLds = "CONL"; // {Confirmation LDS} <blank>
    public const string Continue = "CONT"; // {Continued} Concatenate to previous line with a carriage return or new line. Check spec.
    public const string Copyright = "COPR"; // {Copyright} <COPYRIGHT_GEDCOM_FILE>, <COPYRIGHT_SOURCE_DATA>
    public const string Corporate = "CORP"; // {Corporate} <NAME_OF_BUSINESS>
    public const string Cremation = "CREM"; // {Cremation} <blank>
    public const string Country = "CTRY"; // {Country} <ADDRESS_COUNTRY>
    public const string Data = "DATA"; // {Data} <NAME_OF_SOURCE_DATA>, <blank>
    public const string Date = "DATE"; // {Date} <DATE_VALUE>, <DATE_PERIOD>, <ENTRY_RECORDING_DATE>, <CHANGE_DATE>, <DATE_LDS_ORD>, <TRANSMISSION_DATE>, <PUBLICATION_DATE>
    public const string Death = "DEAT"; // {Death} <blank>
    public const string Descendants = "DESC"; // {Descendants} <GENERATIONS_OF_DESCENDANTS>, <blank>
    public const string DescendantInterest = "DESI"; // {Descendant Int} @<XREF:SUBM>@
    public const string Destination = "DEST"; // {Destination} <RECEIVING_SYSTEM_NAME>
    public const string Divorce = "DIV"; // {Divorce} <blank>
    public const string DivorceFiled = "DIVF"; // {Divorce Filed} <blank>
    public const string PhysicalDescription = "DSCR"; // {Phy Description} <PHYSICAL_DESCRIPTION>
    public const string Education = "EDUC"; // {Education} <SCHOLASTIC_ACHIEVEMENT>
    public const string Email= "EMAIL"; // {Email} <ADDRESS_EMAIL>
    public const string Emigration = "EMIG"; // {Emigration} <blank>
    public const string Endowment = "ENDL"; // {Endowment} <blank>
    public const string Engagement = "ENGA"; // {Engagement} <blank>
    public const string Event = "EVEN"; // {Event} <EVENTS_RECORDED>, [<EVENT_DESCRIPTOR> | <NULL>] <EVENT_TYPE_CITED_FROM>, <blank>
    public const string Fact = "FACT"; // {Fact} <ATTRIBUTE_DESCRIPTOR>
    public const string Family = "FAM"; // {Family} @<XREF:FAM>@ FAM
    public const string FamilyChild = "FAMC"; // {Family Child} @<XREF:FAM>@
    public const string FamilyFile = "FAMF"; // {Family File} <NAME_OF_FAMILY_FILE>
    public const string FamilySpouse = "FAMS"; // {Family Spouse} @<XREF:FAM>@
    public const string Facimilie = "FAX"; // {Facimilie} <ADDRESS_FAX>
    public const string FirstCommunion = "FCOM"; // {First Communion} <blank>
    public const string File = "FILE"; // {File} <FILE_NAME>, <MULTIMEDIA_FILE_REFN>
    public const string Phonetic = "FONE"; // {Phonetic} <NAME_PHONETIC_VARIATION>, <PLACE_PHONETIC_VARIATION>
    public const string Format = "FORM"; // {Format} <MULTIMEDIA_FORMAT>, <PLACE_HIERARCHY>, <GEDCOM_FORM>
    public const string Gedcom = "GEDC"; // {Gedcom} <blank>
    public const string GivenName = "GIVN"; // {Given Name} <NAME_PEICE_GIVEN> 
    public const string Graduation = "GRAD"; // {Graduation} <blank>
    public const string Header = "HEAD"; // {Header} <blank>
    public const string Husband = "HUSB"; // {Husband} @<XREF:INDI>, <blank>
    public const string IndentityNumber = "IDNO"; // {Indent Number} <NATOINAL_ID_NUMBER>
    public const string Immigration = "IMMI"; // {Immigration} <blank>
    public const string Individual = "INDI"; // {Individual} @XREF:INDI@ INDI
    public const string Language = "LANG"; // {Language} <LANGUAGE_PREFERENCE>, <LANGUAGE_OF_TEXT>
    public const string Latitude = "LATI"; // {Latitude} <PLACE_LATITUDE>
    public const string Longitude = "LONG"; // {Longitude} <PLACE_LONGITUDE>
    public const string Map = "MAP"; // {Map} <blank>
    public const string MarriageBann = "MARB"; // {Marriage Bann} <blank>
    public const string MarriageContract = "MARC"; // {Marr Contract} <blank>
    public const string MarriageLicense = "MARL"; // {Marr License} <blank>
    public const string Marriage = "MARR"; // {Marriage} [Y | <NULL], <blank>
    public const string MarriageSettlement = "MARS"; // {Marriage Settlement} <blank>
    public const string Media = "MEDI"; // {Media} <SOURCE_MEDIA_TYPE>
    public const string Name = "NAME"; // {Name} <NAME_PERSONAL>, <SUBMITTER_NAME>, <NAME_OF_REPOSITORY>, <NAME_OF_PRODUCT>
    public const string Nationality = "NATI"; // {Nationality} <NATIONAL_OR_TRIBAL_ORIGIN>
    public const string Naturalization = "NATU"; // {Naturalization} <blank>
    public const string ChildrenCount = "NCHI"; // {Children Count} <COUNT_OF_CHILDREN>
    public const string Nickname = "NICK"; // {Nickname} <NAME_PIECE_NICKNAME>
    public const string MarriageCount = "NMR"; // {Marriage Count} <COUNT_OF_MARRIAGES>
    public const string Note = "NOTE"; // {Note} @<XREF:NOTE>@ NOTE, <SUBMITTER_TEXT>, <GEDCOM_CONTENT_DESCRIPTION>, <NULL>, <blank>
    public const string NamePrefix = "NPFX"; // {Name Prefix} <NAME_PIECE_PREFIX>
    public const string NameSuffix = "NSFX"; // {Name Suffix} <NAME_PIECE_SUFFIX>
    public const string Object = "OBJE"; // {Object} @<XREF:OBJE>@ OBJE, <blank>
    public const string Occupation = "OCCU"; // {Occupation} <OCCUPATION>
    public const string Ordinance = "ORDI"; // {Ordinance} <ORDINANCE_PROCESS_FLAG>, <blank>
    public const string Ordination = "ORDN"; // {Ordination} <blank>
    public const string Page = "PAGE"; // {Page} <WHERE_WITHIN_SOURCE>
    public const string Pedigree = "PEDI"; // {Pedigree} <PEDIGREE_LINKAGE_TYPE>
    public const string Phone = "PHON"; // {Phone} <PHONE_NUMBER>
    public const string Place = "PLAC"; // {Place} <PLACE_NAME>, <SOURCE_JURISDICTION_PLACE>, <PLACE_LIVING_ORDINANCE>, <blank>
    public const string PostalCode = "POST"; // {Postal Code} <ADDRESS_POSTAL_CODE>
    public const string Probate = "PROB"; // {Probate} <blank>
    public const string Property = "PROP"; // {Property} <POSSESSIONS>
    public const string Publication = "PUBL"; // {Publication} <SOURCE_PUBLICATION_FACTS>
    public const string QualityOfData = "QUAY"; // {Quality of Data} <CERTAINTY_ASSESSMENT>
    public const string Reference = "REFN"; // {Reference} <USER_REFERENCE_NUMBER>
    public const string Relationship = "RELA"; // {Relationship} <RELATION_IS_DESCRIPTOR>
    public const string Religion = "RELI"; // {Religion} <RELIGIOUS_AFFILIATION>
    public const string Repository = "REPO"; // {Repository} @<XREF:REPO>@ REPO, <null>, <blank>
    public const string Residence = "RESI"; // {Residence} /*Resides at*/, <blank>
    public const string Restriction = "RESN"; // {Restriction} <RESTRICTION_NOTICE>
    public const string Retirement = "RETI"; // {Retirement} <blank>
    public const string RecordFileNumber = "RFN"; // {Rec File Number} <SUBMITTER_REGISTERED_RFN>, <PERMANENT_RECORD_FILE_NUMBER>
    public const string RecordIdNumber = "RIN"; // {Rec Id Number} <AUTOMATED_RECORD_ID>
    public const string Role = "ROLE"; // {Role} <ROLE_IN_EVENT>
    public const string Romanized = "ROMN"; // {Romanized} <NAME_ROMANIZED_VARIATION>, <PLACE_ROMANIZED_VARIATION>
    public const string Sex = "SEX"; // {Sex} <SEX_VALUE>
    public const string SealingChild = "SLGC"; // {Sealing Child} <blank>
    public const string SealingSpouse = "SLGS"; // {Sealing Spouse} <blank>
    public const string Source = "SOUR"; // {Source} @<XREF:SOUR>@ SOUR, <SOURCE_DESCRIPTION>, <APPROVED_SYSTEM_ID>
    public const string SurnamePrefix = "SPFX"; // {Surn Prefix} <NAME_PIECE_SURNAME_PREFIX>
    public const string SocialSecurityNumber = "SSN"; // {Soc Sec Number} <SOCIAL_SECURITY_NUMBER>
    public const string State = "STAE"; // {State} <ADDRESS_STATE>
    public const string Status = "STAT"; // {Status} <CHILD_LINKAGE_STATUS>, <LDS_SPOUSE_SEALING_DATE_STATUS>, <LDS_CHILD_SEALING_DATE_STATUS>, <LDS_BAPTISM_DATE_STATUS>
    public const string Submitter = "SUBM"; // {Submitter} @<XREF:SUBM>@ SUBM, SUBM @<XREF:SUBM>@
    public const string Submission = "SUBN"; // {Submission} @<XREF:SUBM>@
    public const string Surname = "SURN"; // {Surname} <NAME_PIECE_SURNAME>
    public const string Temple = "TEMP"; // {Temple} <TEMPLE_CODE>
    public const string Text = "TEXT"; // {Text} <TEXT_FROM_SOURCE>
    public const string Time = "TIME"; // {Time} <TIME_VALUE>
    public const string Title = "TITL"; // {Title} <SOURCE_DESCRIPTIVE_TITLE>, <NOBILITY_TYPE_TITLE>, <DESCRIPTIVE_TITLE>
    public const string Trailer = "TRLR"; // {Trailer} <blank>
    public const string Type = "TYPE"; // {Type} <USER_REFERENCE_TYPE>, <EVENT_OR_FACT_CLASSIFICATION>, <NAME_TYPE>, <PHONETIC_TYPE>, <ROMANIZED_TYPE>, <SOURCE_MEDIA_TYPE>
    public const string Version = "VERS"; // {Version} <VERSION_NUMBER>
    public const string Wife = "WIFE"; // {Wife} @<XREF:INDI>@, <blank>
    public const string Will = "WILL"; // {Will} <blank>
    public const string Web = "WWW"; // {Web} <ADDRESS_WEB_PAGE>
}