namespace Gedcom;

/// <summary>
/// A list of all native GEDCOM tags.
/// </summary>
public static class Tag
{
    public const string ABBR = "ABBR"; // {Abbreviation} <SOURCE_FILED_BY_ENTRY>
    public const string ADDR = "ADDR"; // {Address} <ADDRESS_LINE>
    public const string ADOP = "ADOP"; // {Adoption} <blank>
    public const string ADR1 = "ADR1"; // {Address1} <ADDRESS_LINE1>
    public const string ADR2 = "ADR2"; // {Address2} <ADDRESS_LINE2>
    public const string ADR3 = "ADR3"; // {Address3} <ADDRESS_LINE3>
    public const string AFN  = "AFN";  // {AFN} <ANCESTRAL_FILE_NUMBER>
    public const string AGE  = "AGE";  // {Age} <AGE_AT_EVENT>
    public const string AGNC = "AGNC"; // {Agency} <RESPONSIBLE_AGENCY>
    public const string ALIA = "ALIA"; // {Alias} @<XREF:IND>@
    public const string ANCE = "ANCE"; // {Ancestors} <GENERATIONS_OF_ANCESTORS>
    public const string ANCI = "ANCI"; // {Ances Interest} @<XREF:SUBM>@
    public const string ANUL = "ANUL"; // {Annulment} <blank>
    public const string ASSO = "ASSO"; // {Associates} @<XREF:INDI>@
    public const string AUTH = "AUTH"; // {Author} <SOURCE_ORIGINATOR>
    public const string BAPL = "BAPL"; // {Baptism-LDS} <blank>
    public const string BAPM = "BAPM"; // {Baptism} <blank>
    public const string BARM = "BARM"; // {Bar Mitzvah} <blank>
    public const string BASM = "BASM"; // {Bas Mitzvah} <blank>
    public const string BLES = "BLES"; // {Blessing} <blank>
    public const string BIRT = "BIRT"; // {Birth} <blank>
    public const string BOTH = "BOTH"; // {Both} <blank>, <ADOPTED_BY_WHICH_PARENT>
    public const string BURI = "BURI"; // {Burial} <blank>
    public const string CALN = "CALN"; // {Call Number} <SOURCE_CALL_NUMBER>
    public const string CAST = "CAST"; // {Caste} <CASTE_NAME>
    public const string CAUS = "CAUS"; // {Cause} <CAUSE_OF_EVENT>
    public const string CENS = "CENS"; // {Census} <blank>
    public const string CHAN = "CHAN"; // {Change} <blank>
    public const string CHAR = "CHAR"; // {Character} <CHARACTER_SET>
    public const string CHIL = "CHIL"; // {Child} @<XREF:INDI>@
    public const string CHR  = "CHR";  // {Christening} <blank>
    public const string CHRA = "CHRA"; // {Adult Christening} <blank>
    public const string CITY = "CITY"; // {City} <ADDRESS_CITY>
    public const string CONC = "CONC"; // {Concatenation} Concatenate to previous line without a space or carriage return.
    public const string CONF = "CONF"; // {Confirmation} <blank>
    public const string CONL = "CONL"; // {Confirmation LDS} <blank>
    public const string CONT = "CONT"; // {Continued} Concatenate to previous line with a carriage return or new line. Check spec.
    public const string COPR = "COPR"; // {Copyright} <COPYRIGHT_GEDCOM_FILE>, <COPYRIGHT_SOURCE_DATA>
    public const string CORP = "CORP"; // {Corporate} <NAME_OF_BUSINESS>
    public const string CREM = "CREM"; // {Cremation} <blank>
    public const string CTRY = "CTRY"; // {Country} <ADDRESS_COUNTRY>
    public const string DATA = "DATA"; // {Data} <NAME_OF_SOURCE_DATA>, <blank>
    public const string DATE = "DATE"; // {Date} <DATE_VALUE>, <DATE_PERIOD>, <ENTRY_RECORDING_DATE>, <CHANGE_DATE>, <DATE_LDS_ORD>, <TRANSMISSION_DATE>, <PUBLICATION_DATE>
    public const string DEAT = "DEAT"; // {Death} <blank>
    public const string DESC = "DESC"; // {Descendants} <GENERATIONS_OF_DESCENDANTS>, <blank>
    public const string DESI = "DESI"; // {Descendant Int} @<XREF:SUBM>@
    public const string DEST = "DEST"; // {Destination} <RECEIVING_SYSTEM_NAME>
    public const string DIV  = "DIV";  // {Divorce} <blank>
    public const string DIVF = "DIVF"; // {Divorce Filed} <blank>
    public const string DSCR = "DSCR"; // {Phy Description} <PHYSICAL_DESCRIPTION>
    public const string EDUC = "EDUC"; // {Education} <SCHOLASTIC_ACHIEVEMENT>
    public const string EMAIL= "EMAIL";//{Email} <ADDRESS_EMAIL>
    public const string EMIG = "EMIG"; // {Emigration} <blank>
    public const string ENDL = "ENDL"; // {Endowment} <blank>
    public const string ENGA = "ENGA"; // {Engagement} <blank>
    public const string EVEN = "EVEN"; // {Event} <EVENTS_RECORDED>, [<EVENT_DESCRIPTOR> | <NULL>] <EVENT_TYPE_CITED_FROM>, <blank>
    public const string FACT = "FACT"; // {Fact} <ATTRIBUTE_DESCRIPTOR>
    public const string FAM  = "FAM";  // {Family} @<XREF:FAM>@ FAM
    public const string FAMC = "FAMC"; // {Family Child} @<XREF:FAM>@
    public const string FAMF = "FAMF"; // {Family File} <NAME_OF_FAMILY_FILE>
    public const string FAMS = "FAMS"; // {Family Spouse} @<XREF:FAM>@
    public const string FAX  = "FAX";  // {Facimilie} <ADDRESS_FAX>
    public const string FCOM = "FCOM"; // {First Communion} <blank>
    public const string FILE = "FILE"; // {File} <FILE_NAME>, <MULTIMEDIA_FILE_REFN>
    public const string FONE = "FONE"; // {Phonetic} <NAME_PHONETIC_VARIATION>, <PLACE_PHONETIC_VARIATION>
    public const string FORM = "FORM"; // {Format} <MULTIMEDIA_FORMAT>, <PLACE_HIERARCHY>, <GEDCOM_FORM>
    public const string GEDC = "GEDC"; // {Gedcom} <blank>
    public const string GIVN = "GIVN"; // {Given Name} <NAME_PEICE_GIVEN> 
    public const string GRAD = "GRAD"; // {Graduation} <blank>
    public const string HEAD = "HEAD"; // {Header} <blank>
    public const string HUSB = "HUSB"; // {Husband} @<XREF:INDI>, <blank>
    public const string IDNO = "IDNO"; // {Indent Number} <NATOINAL_ID_NUMBER>
    public const string IMMI = "IMMI"; // {Immigration} <blank>
    public const string INDI = "INDI"; // {Individual} @XREF:INDI@ INDI
    public const string LANG = "LANG"; // {Language} <LANGUAGE_PREFERENCE>, <LANGUAGE_OF_TEXT>
    public const string LATI = "LATI"; // {Latitude} <PLACE_LATITUDE>
    public const string LONG = "LONG"; // {Longitude} <PLACE_LONGITUDE>
    public const string MAP  = "MAP";  // {Map} <blank>
    public const string MARB = "MARB"; // {Marriage Bann} <blank>
    public const string MARC = "MARC"; // {Marr Contract} <blank>
    public const string MARL = "MARL"; // {Marr License} <blank>
    public const string MARR = "MARR"; // {Marriage} [Y | <NULL], <blank>
    public const string MARS = "MARS"; // {Marriage Settlement} <blank>
    public const string MEDI = "MEDI"; // {Media} <SOURCE_MEDIA_TYPE>
    public const string NAME = "NAME"; // {Name} <NAME_PERSONAL>, <SUBMITTER_NAME>, <NAME_OF_REPOSITORY>, <NAME_OF_PRODUCT>
    public const string NATI = "NATI"; // {Nationality} <NATIONAL_OR_TRIBAL_ORIGIN>
    public const string NATU = "NATU"; // {Naturalization} <blank>
    public const string NCHI = "NCHI"; // {Children Count} <COUNT_OF_CHILDREN>
    public const string NICK = "NICK"; // {Nickname} <NAME_PIECE_NICKNAME>
    public const string NMR  = "NMR";  // {Marriage Count} <COUNT_OF_MARRIAGES>
    public const string NOTE = "NOTE"; // {Note} @<XREF:NOTE>@ NOTE, <SUBMITTER_TEXT>, <GEDCOM_CONTENT_DESCRIPTION>, <NULL>, <blank>
    public const string NPFX = "NPFX"; // {Name Prefix} <NAME_PIECE_PREFIX>
    public const string NSFX = "NSFX"; // {Name Suffix} <NAME_PIECE_SUFFIX>
    public const string OBJE = "OBJE"; // {Object} @<XREF:OBJE>@ OBJE, <blank>
    public const string OCCU = "OCCU"; // {Occupation} <OCCUPATION>
    public const string ORDI = "ORDI"; // {Ordinance} <ORDINANCE_PROCESS_FLAG>, <blank>
    public const string ORDN = "ORDN"; // {Ordination} <blank>
    public const string PAGE = "PAGE"; // {Page} <WHERE_WITHIN_SOURCE>
    public const string PEDI = "PEDI"; // {Padigree} <PEDIGREE_LINKAGE_TYPE>
    public const string PHON = "PHON"; // {Phone} <PHONE_NUMBER>
    public const string PLAC = "PLAC"; // {Place} <PLACE_NAME>, <SOURCE_JURISDICTION_PLACE>, <PLACE_LIVING_ORDINANCE>, <blank>
    public const string POST = "POST"; // {Postal Code} <ADDRESS_POSTAL_CODE>
    public const string PROB = "PROB"; // {Probate} <blank>
    public const string PROP = "PROP"; // {Property} <POSSESSIONS>
    public const string PUBL = "PUBL"; // {Publication} <SOURCE_PUBLICATION_FACTS>
    public const string QUAY = "QUAY"; // {Quality of Data} <CERTAINTY_ASSESSMENT>
    public const string REFN = "REFN"; // {Reference} <USER_REFERENCE_NUMBER>
    public const string RELA = "RELA"; // {Relationship} <RELATION_IS_DESCRIPTOR>
    public const string RELI = "RELI"; // {Religion} <RELIGIOUS_AFFILIATION>
    public const string REPO = "REPO"; // {Repository} @<XREF:REPO>@ REPO, <null>, <blank>
    public const string RESI = "RESI"; // {Residence } /*Resides at*/, <blank>
    public const string RESN = "RESN"; // {Restriction} <RESTRICTION_NOTICE>
    public const string RETI = "RETI"; // {Retirement} <blank>
    public const string RFN  = "RFN";  // {Rec File Number} <SUBMITTER_REGISTERED_RFN>, <PERMANENT_RECORD_FILE_NUMBER>
    public const string RIN  = "RIN";  // {Rec Id Number} <AUTOMATED_RECORD_ID>
    public const string ROLE = "ROLE"; // {Role} <ROLE_IN_EVENT>
    public const string ROMN = "ROMN"; // {Romanized} <NAME_ROMANIZED_VARIATION>, <PLACE_ROMANIZED_VARIATION>
    public const string SEX  = "SEX";  // {Sex} <SEX_VALUE>
    public const string SLGC = "SLGC"; // {Sealing Child} <blank>
    public const string SLGS = "SLGS"; // {Sealing Spouse} <blank>
    public const string SOUR = "SOUR"; // {Source} @<XREF:SOUR>@ SOUR, <SOURCE_DESCRIPTION>, <APPROVED_SYSTEM_ID>
    public const string SPFX = "SPFX"; // {Surn Prefix} <NAME_PIECE_SURNAME_PREFIX>
    public const string SSN  = "SSN";  // {Soc Sec Number} <SOCIAL_SECURITY_NUMBER>
    public const string STAE = "STAE"; // {State} <ADDRESS_STATE>
    public const string STAT = "STAT"; // {Status} <CHILD_LINKAGE_STATUS>, <LDS_SPOUSE_SEALING_DATE_STATUS>, <LDS_CHILD_SEALING_DATE_STATUS>, <LDS_BAPTISM_DATE_STATUS>
    public const string SUBM = "SUBM"; // {Submitter} @<XREF:SUBM>@ SUBM, SUBM @<XREF:SUBM>@
    public const string SUBN = "SUBN"; // {Submission} @<XREF:SUBM>@
    public const string SURN = "SURN"; // {Surname} <NAME_PIECE_SURNAME>
    public const string TEMP = "TEMP"; // {Temple} <TEMPLE_CODE>
    public const string TEXT = "TEXT"; // {Text} <TEXT_FROM_SOURCE>
    public const string TIME = "TIME"; // {Time} <TIME_VALUE>
    public const string TITL = "TITL"; // {Title} <SOURCE_DESCRIPTIVE_TITLE>, <NOBILITY_TYPE_TITLE>, <DESCRIPTIVE_TITLE>
    public const string TRLR = "TRLR"; // {Trailer} <blank>
    public const string TYPE = "TYPE"; // {Type} <USER_REFERENCE_TYPE>, <EVENT_OR_FACT_CLASSIFICATION>, <NAME_TYPE>, <PHONETIC_TYPE>, <ROMANIZED_TYPE>, <SOURCE_MEDIA_TYPE>
    public const string VERS = "VERS"; // {Version} <VERSION_NUMBER>
    public const string WIFE = "WIFE"; // {Wife} @<XREF:INDI>@, <blank>
    public const string WILL = "WILL"; // {Will} <blank>
    public const string WWW  = "WWW";  // {Web} <ADDRESS_WEB_PAGE>
}