namespace Gedcom;

public static class C // Constants
{
    public const string _ENV = "_ENV";
    public const string _TREE = "_TREE";
    public const string ABBR = "ABBR"; // <SOURCE_FILED_BY_ENTRY>
    public const string ADDR = "ADDR"; // <ADDRESS_LINE>
    public const string ADOP = "ADOP"; // <blank>
    public const string ADR1 = "ADR1"; // <ADDRESS_LINE1>
    public const string ADR2 = "ADR2"; // <ADDRESS_LINE2>
    public const string ADR3 = "ADR3"; // <ADDRESS_LINE3>
    public const string AFN = "AFN"; // <ANCESTRAL_FILE_NUMBER>
    public const string AGE = "AGE"; // <AGE_AT_EVENT>
    public const string AGNC = "AGNC"; // <RESPONSIBLE_AGENCY>
    public const string ALIA = "ALIA"; // @<XREF:IND>@
    public const string ANCE = "ANCE"; // <GENERATIONS_OF_ANCESTORS>
    public const string ANCI = "ANCI"; // @<XREF:SUBM>@
    public const string ANUL = "ANUL"; // <blank>
    public const string ASSO = "ASSO"; // @<XREF:INDI>@
    public const string AUTH = "AUTH"; // <SOURCE_ORIGINATOR>
    public const string BAPL = "BAPL"; // <blank>
    public const string BAPM = "BAPM"; // <blank>
    public const string BARM = "BARM"; // <blank>
    public const string BASM = "BASM"; // <blank>
    public const string BLES = "BLES"; // <blank>
    public const string BIRT = "BIRT"; // <blank>
    public const string BOTH = "BOTH"; // <blank>, <ADOPTED_BY_WHICH_PARENT>
    public const string BURI = "BURI"; // <blank>
    public const string CALN = "CALN"; // <SOURCE_CALL_NUMBER>
    public const string CAST = "CAST"; // <CASTE_NAME>
    public const string CAUS = "CAUS"; // <CAUSE_OF_EVENT>
    public const string CENS = "CENS"; // <blank>
    public const string CHAN = "CHAN"; // <blank>
    public const string CHAR = "CHAR"; // <CHARACTER_SET>
    public const string CHIL = "CHIL"; // @<XREF:INDI>@
    public const string CHR = "CHR"; // <blank>
    public const string CHRA = "CHRA"; // <blank>
    public const string CREM = "CREM"; // <blank>
    public const string CITY = "CITY"; // <ADDRESS_CITY>
    public const string CONC = "CONC"; // Concatenation: Concatenate to previous line without a space or carriage return.
    public const string CONL = "CONL"; // <blank>
    public const string CONF = "CONF"; // <blank>
    public const string CONT = "CONT"; // Continued: Concatenate to previous line with a carriage return or new line. Check spec.
    public const string COPR = "COPR"; // <COPYRIGHT_GEDCOM_FILE>, <COPYRIGHT_SOURCE_DATA>
    public const string CORP = "CORP"; // <NAME_OF_BUSINESS>
    public const string CTRY = "CTRY"; // <ADDRESS_COUNTRY>
    public const string DATA = "DATA"; // <NAME_OF_SOURCE_DATA>, <blank>
    public const string DATE = "DATE"; // <DATE_VALUE>, <DATE_PERIOD>, <ENTRY_RECORDING_DATE>, <CHANGE_DATE>, <DATE_LDS_ORD>, <TRANSMISSION_DATE>, <PUBLICATION_DATE>
    public const string DEAT = "DEAT"; // <blank>
    public const string DESC = "DESC"; // <GENERATIONS_OF_DESCENDANTS>, <blank>
    public const string DESI = "DESI"; // @<XREF:SUBM>@
    public const string DEST = "DEST"; // <RECEIVING_SYSTEM_NAME>
    public const string DIV = "DIV"; // <blank>
    public const string DIVF = "DIVF"; // <blank>
    public const string DSCR = "DSCR"; // <PHYSICAL_DESCRIPTION>
    public const string EDUC = "EDUC"; // <SCHOLASTIC_ACHIEVEMENT>
    public const string EMAIL = "EMAIL"; // <ADDRESS_EMAIL>
    public const string EMIG = "EMIG"; // <blank>
    public const string Empty = "EMPTY"; // For the empty Record
    public const string ENDL = "ENDL"; // <blank>
    public const string ENGA = "ENGA"; // <blank>
    public const string EVEN = "EVEN"; // <EVENTS_RECORDED>, [<EVENT_DESCRIPTOR> | <NULL>] <EVENT_TYPE_CITED_FROM>, <blank>
    public const string FAM = "FAM"; // @<XREF:FAM>@ FAM
    public const string FACT = "FACT"; // <ATTRIBUTE_DESCRIPTOR>
    public const string FAMC = "FAMC"; // @<XREF:FAM>@
    public const string FAMF = "FAMF"; // <NAME_OF_FAMILY_FILE>
    public const string FAMS = "FAMS"; // @<XREF:FAM>@
    public const string FAX = "FAX"; // <ADDRESS_FAX>
    public const string FCOM = "FCOM"; // <blank>
    public const string FILE = "FILE"; // <FILE_NAME>, <MULTIMEDIA_FILE_REFN>
    public const string FONE = "FONE"; // <NAME_PHONETIC_VARIATION>, <PLACE_PHONETIC_VARIATION>
    public const string FORM = "FORM"; // <MULTIMEDIA_FORMAT>, <PLACE_HIERARCHY>, <GEDCOM_FORM>
    public const string GEDC = "GEDC"; // <blank>
    public const string GIVN = "GIVN"; // <NAME_PEICE_GIVEN> 
    public const string GRAD = "GRAD"; // <blank>
    public const string HEAD = "HEAD"; // <blank>
    public const string HUSB = "HUSB"; // @<XREF:INDI>, <blank>
    public const string INDI = "INDI"; // @XREF:INDI@ INDI
    public const string IDNO = "IDNO"; // <NATOINAL_ID_NUMBER>
    public const string IMMI = "IMMI"; // <blank>
    public const string LANG = "LANG"; // <LANGUAGE_PREFERENCE>, <LANGUAGE_OF_TEXT>
    public const string LATI = "LATI"; // <PLACE_LATITUDE>
    public const string LONG = "LONG"; // <PLACE_LONGITUDE>
    public const string MAP = "MAP"; // <blank>
    public const string MARB = "MARB"; // <blank>
    public const string MARC = "MARC"; // <blank>
    public const string MARL = "MARL"; // <blank>
    public const string MARR = "MARR"; // [Y | <NULL], <blank>
    public const string MARS = "MARS"; // <blank>
    public const string MEDI = "MEDI"; // <SOURCE_MEDIA_TYPE>
    public const string NAME = "NAME"; // <NAME_PERSONAL>, <SUBMITTER_NAME>, <NAME_OF_REPOSITORY>, <NAME_OF_PRODUCT>
    public const string NATI = "NATI"; // <NATIONAL_OR_TRIBAL_ORIGIN>
    public const string NATU = "NATU"; // <blank>
    public const string NCHI = "NCHI"; // <COUNT_OF_CHILDREN>
    public const string NICK = "NICK"; // <NAME_PIECE_NICKNAME>
    public const string NMR = "NMR"; // <COUNT_OF_MARRIAGES>
    public const string NOTE = "NOTE"; // @<XREF:NOTE>@ NOTE, <SUBMITTER_TEXT>, <GEDCOM_CONTENT_DESCRIPTION>, <NULL>, <blank>
    public const string NPFX = "NPFX"; // <NAME_PIECE_PREFIX>
    public const string NSFX = "NSFX"; // <NAME_PIECE_SUFFIX>
    public const string OBJE = "OBJE"; // @<XREF:OBJE>@ OBJE, <blank>
    public const string OCCU = "OCCU"; // <OCCUPATION>
    public const string ORDI = "ORDI"; // <ORDINANCE_PROCESS_FLAG>, <blank>
    public const string ORDN = "ORDN"; // <blank>
    public const string PAGE = "PAGE"; // <WHERE_WITHIN_SOURCE>
    public const string PEDI = "PEDI"; // <PEDIGREE_LINKAGE_TYPE>
    public const string PHON = "PHON"; // <PHONE_NUMBER>
    public const string PLAC = "PLAC"; // <PLACE_NAME>, <SOURCE_JURISDICTION_PLACE>, <PLACE_LIVING_ORDINANCE>, <blank>
    public const string POST = "POST"; // <ADDRESS_POSTAL_CODE>
    public const string PROB = "PROB"; // <blank>
    public const string PROP = "PROP"; // <POSSESSIONS>
    public const string PUBL = "PUBL"; // <SOURCE_PUBLICATION_FACTS>
    public const string QUAY = "QUAY"; // <CERTAINTY_ASSESSMENT>
    public const string REFN = "REFN"; // <USER_REFERENCE_NUMBER>
    public const string RELA = "RELA"; // <RELATION_IS_DESCRIPTOR>
    public const string RELI = "RELI"; // <RELIGIOUS_AFFILIATION>
    public const string REPO = "REPO"; // @<XREF:REPO>@ REPO, <null>, <blank>
    public const string RESI = "RESI"; // /*Resides at*/, <blank>
    public const string RESN = "RESN"; // <RESTRICTION_NOTICE>
    public const string RETI = "RETI"; // <blank>
    public const string RFN = "RFN"; // <SUBMITTER_REGISTERED_RFN>, <PERMANENT_RECORD_FILE_NUMBER>
    public const string RIN = "RIN"; // <AUTOMATED_RECORD_ID>
    public const string ROLE = "ROLE"; // <ROLE_IN_EVENT>
    public const string ROMN = "ROMN"; // <NAME_ROMANIZED_VARIATION>, <PLACE_ROMANIZED_VARIATION>
    public const string SEX = "SEX"; // <SEX_VALUE>
    public const string SLGC = "SLGC"; // <blank>
    public const string SLGS = "SLGS"; // <blank>
    public const string SOUR = "SOUR"; // @<XREF:SOUR>@ SOUR, <SOURCE_DESCRIPTION>, <APPROVED_SYSTEM_ID>
    public const string SPFX = "SPFX"; // <NAME_PIECE_SURNAME_PREFIX>
    public const string SSN = "SSN"; // <SOCIAL_SECURITY_NUMBER>
    public const string STAE = "STAE"; // <ADDRESS_STATE>
    public const string STAT = "STAT"; // <CHILD_LINKAGE_STATUS>, <LDS_SPOUSE_SEALING_DATE_STATUS>, <LDS_CHILD_SEALING_DATE_STATUS>, <LDS_BAPTISM_DATE_STATUS>
    public const string SUBM = "SUBM"; // @<XREF:SUBM>@ SUBM, SUBM @<XREF:SUBM>@
    public const string SUBN = "SUBN"; // @<XREF:SUBM>@
    public const string SURN = "SURN"; // <NAME_PIECE_SURNAME>
    public const string TEMP = "TEMP"; // <TEMPLE_CODE>
    public const string TEXT = "TEXT"; // <TEXT_FROM_SOURCE>
    public const string TIME = "TIME"; // <TIME_VALUE>
    public const string TITL = "TITL"; // <SOURCE_DESCRIPTIVE_TITLE>, <NOBILITY_TYPE_TITLE>, <DESCRIPTIVE_TITLE>
    public const string TRLR = "TRLR"; // <blank>
    public const string TYPE = "TYPE"; // <USER_REFERENCE_TYPE>, <EVENT_OR_FACT_CLASSIFICATION>, <NAME_TYPE>, <PHONETIC_TYPE>, <ROMANIZED_TYPE>, <SOURCE_MEDIA_TYPE>
    public const string VERS = "VERS"; // <VERSION_NUMBER>
    public const string WIFE = "WIFE"; // @<XREF:INDI>@, <blank>
    public const string WILL = "WILL"; // <blank>
    public const string WWW = "WWW"; // <ADDRESS_WEB_PAGE>
    public const string XREF = "Xref";
}